services:
  goflow2:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: netsampler/goflow2
    user: root # because docker-compose mount as root
    ports:
      - '8080:8080'
      # - '6343:6343/udp'
      - '2055:2055/udp'
    command:
      - -mapping=/field-map.yaml
      - -transport=file
      - -transport.file=/var/log/goflow/goflow2.log
      #- -format=json
      - -format=bin
    restart: unless-stopped
    #logging:
    #  driver: gelf
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "flows"
    volumes:
      - ./logs:/var/log/goflow
      - ./field-map.yaml:/field-map.yaml
