services:
  goflow2:
    image: netsampler/goflow2
    user: root # because docker-compose mount as root
    ports:
      - '8080:8080'
      - '2055:2055/udp'
    command:
      - -mapping=/field-map.yaml
      - -transport=file
      - -transport.file=/var/log/goflow/goflow2.log
      - -format=bin
      # Uncomment to remove the 0x0A record separator
      #- -transport.file.sep=
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Maximum size of each log file before rotation
        max-file: "5"  # Maximum number of log files to retain
    volumes:
      - ./logs:/var/log/goflow
      - ./field-map.yaml:/field-map.yaml
